// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUspra6bPAyKZ43dU9HozDVop06fsekD4',
    appId: '1:57449337991:web:3f8825bb2b5f2f77f95422',
    messagingSenderId: '57449337991',
    projectId: 'restaurantapp-f0919',
    authDomain: 'restaurantapp-f0919.firebaseapp.com',
    storageBucket: 'restaurantapp-f0919.appspot.com',
    measurementId: 'G-Q5ZY4L1CZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIhnZTBH_2kikI5uJS7rZidiPblSsjZ3M',
    appId: '1:57449337991:android:0190c9eb05a2cf8ef95422',
    messagingSenderId: '57449337991',
    projectId: 'restaurantapp-f0919',
    storageBucket: 'restaurantapp-f0919.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1TEVA0KoqUDxBAP1XNMWVCmi5EJfcUNM',
    appId: '1:57449337991:ios:5d79fb050df2ec85f95422',
    messagingSenderId: '57449337991',
    projectId: 'restaurantapp-f0919',
    storageBucket: 'restaurantapp-f0919.appspot.com',
    iosBundleId: 'com.example.restaurantApp',
  );
}
